const TYPE =  {
  HOME : {
    CHANGE_LAYOUTS : 'CHANGE_LAYOUTS',
    CHANGE_THEME : 'CHANGE_THEME'
  },
  CHAT : {
    CHANGE_USER_CHAT_DEFAULT : 'CHANGE_USER_CHAT_DEFAULT'
  }
}
export default TYPE;