const TYPE =  {
  HOME : {
    CHANGE_LAYOUTS: 'CHANGE_LAYOUTS',
    CHANGE_THEME  : 'CHANGE_THEME'
  },
  CHAT : {
    CHANGE_USER_CHAT_DEFAULT: 'CHANGE_USER_CHAT_DEFAULT'
  },
  SOCCKET : {
    SET_SOCKET_IO: "SET_SOCKET_IO"
  }
}
export default TYPE;